name: .NET Microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      ProductCatalog_Path: ProductCatalog
      ApiGateway_Path: ApiGateway
      ConfigServer_Path: ConfigServer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Opção 1: Build and run ApiGateway in background (executa em segundo plano)
    #- name: Build and run ApiGateway in background
    #  run: |
    #    cd $env:ApiGateway_Path
    #    dotnet build --configuration ${{ matrix.configuration }}
    #    nohup dotnet run --configuration ${{ matrix.configuration }} &

    # Opção 2: Apenas Build ApiGateway (não executa o servidor)
    - name: Build ApiGateway
      run: |
        cd $env:ApiGateway_Path
        dotnet build --configuration ${{ matrix.configuration }}

    # Opção 3: Build and run ApiGateway with timeout (limita o tempo de execução)
    #- name: Build and run ApiGateway with timeout
    #  run: |
    #    cd $env:ApiGateway_Path
    #    dotnet build --configuration ${{ matrix.configuration }}
    #    timeout 30s dotnet run --configuration ${{ matrix.configuration }}

    - name: Build ConfigServer
      run: |
        cd $env:ConfigServer_Path
        dotnet build --configuration ${{ matrix.configuration }}

    - name: Skip EurekaServer
      run: echo "EurekaServer is a Java project and will be skipped in this pipeline."
