name: .NET Microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      ProductCatalog_Path: ProductCatalog
      ApiGateway_Path: ApiGateway
      ConfigServer_Path: ConfigServer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build and run ApiGateway
      run: |
        cd $env:ApiGateway_Path
        dotnet build --configuration ${{ matrix.configuration }}
        dotnet run --configuration ${{ matrix.configuration }}

    - name: Build and run ConfigServer
      run: |
        cd $env:ConfigServer_Path
        dotnet build --configuration ${{ matrix.configuration }}
        dotnet run --configuration ${{ matrix.configuration }}

    - name: Skip EurekaServer
      run: echo "EurekaServer is a Java project and will be skipped in this pipeline."
